"""phase2_modules_problem_change_asset

Revision ID: ae2bcdc8e643
Revises: f04a7ec6b3e5
Create Date: 2026-02-12 23:14:27.915112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2bcdc8e643'
down_revision: Union[str, Sequence[str], None] = 'f04a7ec6b3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_assets_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assets_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_assets_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_assigned_user_id'), 'assets', ['assigned_user_id'], unique=False)
    op.create_index('ix_assets_org_identifier', 'assets', ['organization_id', 'identifier'], unique=True)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_change_requests_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_change_requests_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_change_requests_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests'))
    )
    op.create_index(op.f('ix_change_requests_organization_id'), 'change_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_problems_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_problems_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_problems_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index(op.f('ix_problems_organization_id'), 'problems', ['organization_id'], unique=False)
    op.create_index(op.f('ix_problems_status'), 'problems', ['status'], unique=False)
    op.create_table('change_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('change_request_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_change_approvals_approver_id_users')),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name=op.f('fk_change_approvals_change_request_id_change_requests')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_change_approvals_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_approvals'))
    )
    op.create_index(op.f('ix_change_approvals_change_request_id'), 'change_approvals', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_change_approvals_organization_id'), 'change_approvals', ['organization_id'], unique=False)
    op.create_table('problem_ticket_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_problem_ticket_links_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_problem_ticket_links_organization_id_organizations')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_ticket_links_problem_id_problems')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_problem_ticket_links_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_ticket_links'))
    )
    op.create_index(op.f('ix_problem_ticket_links_organization_id'), 'problem_ticket_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_problem_ticket_links_problem_id'), 'problem_ticket_links', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_ticket_links_ticket_id'), 'problem_ticket_links', ['ticket_id'], unique=False)
    op.create_table('ticket_asset_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_ticket_asset_links_asset_id_assets')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ticket_asset_links_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ticket_asset_links_organization_id_organizations')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_asset_links_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_asset_links'))
    )
    op.create_index(op.f('ix_ticket_asset_links_asset_id'), 'ticket_asset_links', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ticket_asset_links_organization_id'), 'ticket_asset_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ticket_asset_links_ticket_id'), 'ticket_asset_links', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_asset_links_ticket_id'), table_name='ticket_asset_links')
    op.drop_index(op.f('ix_ticket_asset_links_organization_id'), table_name='ticket_asset_links')
    op.drop_index(op.f('ix_ticket_asset_links_asset_id'), table_name='ticket_asset_links')
    op.drop_table('ticket_asset_links')
    op.drop_index(op.f('ix_problem_ticket_links_ticket_id'), table_name='problem_ticket_links')
    op.drop_index(op.f('ix_problem_ticket_links_problem_id'), table_name='problem_ticket_links')
    op.drop_index(op.f('ix_problem_ticket_links_organization_id'), table_name='problem_ticket_links')
    op.drop_table('problem_ticket_links')
    op.drop_index(op.f('ix_change_approvals_organization_id'), table_name='change_approvals')
    op.drop_index(op.f('ix_change_approvals_change_request_id'), table_name='change_approvals')
    op.drop_table('change_approvals')
    op.drop_index(op.f('ix_problems_status'), table_name='problems')
    op.drop_index(op.f('ix_problems_organization_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_organization_id'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index('ix_assets_org_identifier', table_name='assets')
    op.drop_index(op.f('ix_assets_assigned_user_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
