"""add_rules_and_sla_tables

Revision ID: ea345e95baa4
Revises: 1c1c6716c2ab
Create Date: 2026-02-12 22:19:45.506584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea345e95baa4'
down_revision: Union[str, Sequence[str], None] = '1c1c6716c2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index(op.f('ix_rules_event_type'), 'rules', ['event_type'], unique=False)
    op.create_index(op.f('ix_rules_execution_order'), 'rules', ['execution_order'], unique=False)
    op.create_table('rule_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_actions_rule_id_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_actions'))
    )
    op.create_index(op.f('ix_rule_actions_rule_id'), 'rule_actions', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_actions_rule_id'), table_name='rule_actions')
    op.drop_table('rule_actions')
    op.drop_index(op.f('ix_rules_execution_order'), table_name='rules')
    op.drop_index(op.f('ix_rules_event_type'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
