"""add_escalation_level

Revision ID: f04a7ec6b3e5
Revises: b0dfdbb55d57
Create Date: 2026-02-12 22:29:21.778122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04a7ec6b3e5'
down_revision: Union[str, Sequence[str], None] = 'b0dfdbb55d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('escalation_level', sa.Integer(), nullable=False, server_default="0"))
    op.create_index(op.f('ix_tickets_escalation_level'), 'tickets', ['escalation_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_escalation_level'), table_name='tickets')
    op.drop_column('tickets', 'escalation_level')
    # ### end Alembic commands ###
